version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - riskengine

  riskengine:
    build:
      context: .
      dockerfile: riskengine.Dockerfile
    ports:
      - "9090:9090"
